#!/bin/sh

VERSION="1.0.12"

. /opt/etc/tpws/tpws.conf

TPWS_BIN=/opt/usr/bin/tpws

is_running() {
  PID_RUNNING=$(pgrep -nx "$TPWS_BIN" 2>/dev/null)

  if [ -z "$PID_RUNNING" ]; then
    return 1
  fi

  if [ ! -f "$PIDFILE" ]; then
    return 1
  fi

  PID_SAVED=$(cat "$PIDFILE")

  if [ "$PID_RUNNING" -ne "$PID_SAVED" ]; then
    return 1
  fi

  if ! kill -0 $(cat "$PIDFILE"); then
    return 1
  fi

  # 0 = true, 1 = false
  return 0
}

start() {
  if is_running; then
    echo 'Service TPWS is already running' >&2
    return 1
  fi

  BIND_IFACE=""
  for IFACE in $LOCAL_INTERFACE; do
    BIND_IFACE="$BIND_IFACE --bind-iface4=$IFACE"
    if [ "$IPV6_ENABLED" -eq "1" ]; then
      BIND_IFACE="$BIND_IFACE --bind-iface6=$IFACE"
    fi
    echo "Bind to local interface: $IFACE"
  done

  $TPWS_BIN --daemon $BIND_IFACE --port=$BIND_PORT --pidfile=$PIDFILE $TPWS_ARGS $TPWS_EXTRA_ARGS

  firewall_start_v4
  firewall_start_v6

  echo 'Started TPWS service'
}

stop() {
  firewall_stop_v4
  firewall_stop_v6

  if ! is_running; then
    echo 'Service TPWS is not running' >&2
    return 1
  fi

  echo 'Stopping TPWS service...'
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
}

reload() {
  if ! is_running; then
    echo 'Service TPWS is not running' >&2
    return 1
  fi

  echo 'Reloading TPWS service...'
  kill -1 $(cat "$PIDFILE")
}

firewall_start_v4() {
  if [ -z "$(iptables-save 2>/dev/null | grep "to-ports $BIND_PORT$")" ]; then
    for IFACE in $LOCAL_INTERFACE; do
      iptables -t nat -A PREROUTING -i $IFACE -p tcp --dport 80 -j REDIRECT --to-port $BIND_PORT
      iptables -t nat -A PREROUTING -i $IFACE -p tcp --dport 443 -j REDIRECT --to-port $BIND_PORT
      #iptables -t nat -A PREROUTING -i $IFACE -p udp --dport 443 -j REDIRECT --to-port $BIND_PORT
    done
  fi
}

firewall_stop_v4() {
  if [ -n "$(iptables-save 2>/dev/null | grep "to-ports $BIND_PORT$")" ]; then
    for IFACE in $LOCAL_INTERFACE; do
      iptables -t nat -D PREROUTING -i $IFACE -p tcp --dport 80 -j REDIRECT --to-port $BIND_PORT
      iptables -t nat -D PREROUTING -i $IFACE -p tcp --dport 443 -j REDIRECT --to-port $BIND_PORT
      #iptables -t nat -D PREROUTING -i $IFACE -p udp --dport 443 -j REDIRECT --to-port $BIND_PORT
    done
  fi
}

firewall_start_v6() {
  if [ "$IPV6_ENABLED" -ne "1" ]; then
    return
  fi

  if [ -z "$(ip6tables-save 2>/dev/null | grep "to-ports $BIND_PORT$")" ]; then
    for IFACE in $LOCAL_INTERFACE; do
      ip6tables -t nat -A PREROUTING -i $IFACE -p tcp --dport 80 -j REDIRECT --to-port $BIND_PORT
      ip6tables -t nat -A PREROUTING -i $IFACE -p tcp --dport 443 -j REDIRECT --to-port $BIND_PORT
      ip6tables -t nat -A PREROUTING -i $IFACE -p udp --dport 443 -j REDIRECT --to-port $BIND_PORT
    done
  fi
}

firewall_stop_v6() {
  if [ "$IPV6_ENABLED" -ne "1" ]; then
    return
  fi

  if [ -n "$(ip6tables-save 2>/dev/null | grep "to-ports $BIND_PORT$")" ]; then
    for IFACE in $LOCAL_INTERFACE; do
      ip6tables -t nat -D PREROUTING -i $IFACE -p tcp --dport 80 -j REDIRECT --to-port $BIND_PORT
      ip6tables -t nat -D PREROUTING -i $IFACE -p tcp --dport 443 -j REDIRECT --to-port $BIND_PORT
      ip6tables -t nat -D PREROUTING -i $IFACE -p udp --dport 443 -j REDIRECT --to-port $BIND_PORT
    done
  fi
}

status() {
  if is_running; then
    echo 'Service TPWS is running'
  else
    echo 'Service TPWS is stopped'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  reload)
    reload
    ;;
  firewall-iptables)
    firewall_start_v4
    ;;
  firewall-ip6tables)
    firewall_start_v6
    ;;
  version|-v|--version)
    echo "tpws-keenetic version: $VERSION"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status|version}"
esac
